



.PHONY:clean

clean:
	#rm all.hmm.ps.len
	#rm dbCAN-fam-HMMs.txt
	#rm hmmscan-parser.sh
	rm dbCAN-fam-HMMs.txt.h3f
	rm dbCAN-fam-HMMs.txt.h3i
	rm dbCAN-fam-HMMs.txt.h3m
	rm dbCAN-fam-HMMs.txt.h3p
	rm example.dbCAN
	rm example.fasta.annotation
	rm example.fasta.dbCAN
	rm example.fasta.out.dm

